import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const origin=process.env.TEST_ORIGIN??'http://127.0.0.1:5173';
const target=await fetch(`http://127.0.0.1:9222/json/new?${origin}`,{method:'PUT'}).then(r=>r.json());
const socket=new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
let serial=0;const pending=new Map();const exceptions=[];
socket.onmessage=event=>{const v=JSON.parse(event.data);if(v.method==='Runtime.exceptionThrown')exceptions.push(v.params.exceptionDetails.text);if(!v.id)return;const p=pending.get(v.id);if(!p)return;pending.delete(v.id);v.error?p.reject(new Error(v.error.message)):p.resolve(v.result);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const v=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(v.exceptionDetails)throw new Error(v.exceptionDetails.exception?.description??v.exceptionDetails.text);return v.result.value;};
const waitFor=async(expression,timeout=20000)=>{const at=Date.now();while(Date.now()-at<timeout){if(await evaluate(expression))return;await new Promise(resolve=>setTimeout(resolve,100));}throw new Error('Timed out: '+expression);};
const click=async text=>{
  const point=await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.includes(${JSON.stringify(text)}));if(!b||b.disabled)return null;b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};})()`);
  assert(point,`Button ${text} must be enabled`);
  await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});
  await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
};
const type=async(selector,value)=>{await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);await new Promise(r=>setTimeout(r,150));};
const shot=async name=>{const v=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(`/tmp/${name}.png`,Buffer.from(v.data,'base64'));};
await send('Page.enable');await send('Runtime.enable');await send('Network.enable');
await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__audioFailures=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const result=play.call(this);result?.catch(error=>window.__audioFailures.push({name:error.name,message:error.message,url:this.currentSrc,code:this.error?.code}));return result;};`});
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await waitFor("Boolean(document.querySelector('.decoding-coach'))");
await evaluate("localStorage.removeItem('ouvir-ingles:v4:decoding-progress');localStorage.removeItem('ouvir-ingles:v4:decoding-settings');location.reload()");
await waitFor("Boolean(document.querySelector('.decoding-coach'))");
await shot('listening-coach-desktop');
assert.equal(await evaluate("document.querySelectorAll('.coach-weeks button').length"),8);
assert.equal(await evaluate("document.querySelectorAll('.coach-lessons article').length"),3);
await click('Começar próxima lição');
await waitFor("Boolean(document.querySelector('.coach-session'))");
const data=await fetch(`${origin}/data/decoding.json`).then(r=>r.json());
const lesson=data.lessons[0];const first=data.clips.find(c=>c.id===lesson.clipIds[0]);
assert.equal(await evaluate(`document.body.innerText.includes(${JSON.stringify(first.english)})`),false,'Initial listening must not reveal transcript');
await click('Ouvir em 1×');
await waitFor("document.querySelector('.audio-orb').classList.contains('playing')");
await waitFor("!document.querySelector('.audio-orb').classList.contains('playing')",25000);
await click('Escrever o que ouvi');
await type('#first-dictation','I go on computer and talk with my friends');
await click('Revelar e comparar');
await waitFor("Boolean(document.querySelector('.coach-original'))");
assert.equal(await evaluate(`document.querySelector('.coach-original').textContent === ${JSON.stringify(first.english)}`),true);
await evaluate("document.querySelector('.coach-error-tags input').click()");
await shot('listening-comparison');
await click('Criar microloop');
await waitFor("Boolean(document.querySelector('.coach-word-selection'))");
await evaluate("document.querySelectorAll('.coach-word-selection button')[2].click();document.querySelectorAll('.coach-word-selection button')[5].click()");
const bounds=await evaluate("[...document.querySelectorAll('.coach-range-controls input')].map(x=>Number(x.value))");
assert(bounds[1]>bounds[0]);assert(bounds[0]>=first.start);assert(bounds[1]<=first.end);
await click('Loop 5×');
await new Promise(r=>setTimeout(r,800));
await click('Parar');
await click('Imitar a voz');await click('Falar junto');
await new Promise(r=>setTimeout(r,500));
await click('Esconder texto e testar');
await waitFor("Boolean(document.querySelector('#blind-dictation'))");
assert.equal(await evaluate(`document.body.innerText.includes(${JSON.stringify(first.english)})`),false,'Blind phase must remove the transcript');
await click('Ouvir em 1×');
await waitFor("document.querySelector('.coach-blind-player small').textContent.includes('Áudio ouvido')");
await type('#blind-dictation',first.english);await click('Conferir este teste');
await waitFor("Boolean(document.querySelector('.coach-blind-result'))");
assert.equal(await evaluate("document.querySelector('.coach-result-number').textContent"),'100%');
await click('Claro em 1×');
await waitFor("document.querySelector('.coach-session-head h2').textContent.includes('Trecho 2')");
const second=data.clips.find(c=>c.id===lesson.clipIds[1]);
assert.equal(await evaluate(`document.body.innerText.includes(${JSON.stringify(second.english)})`),false,'Automatic next question must remain blind');
const saved=await evaluate("JSON.parse(localStorage.getItem('ouvir-ingles:v4:decoding-progress'))");
assert.equal(saved.attempts.length,1);assert.equal(saved.memories[first.id].reviews,0);assert.equal(saved.memories[first.id].delayedScore,undefined);
await click('Sair da sessão');
await waitFor("Boolean(document.querySelector('.decoding-coach'))");
await click('Abrir laboratório de sons');
await waitFor("Boolean(document.querySelector('.coach-contrast'))");
await click('Ouvir palavra surpresa');
await waitFor("[...document.querySelectorAll('.coach-contrast button')].filter(b=>b.textContent==='ship'||b.textContent==='sheep').every(b=>!b.disabled)");
await click('ship');await waitFor("Boolean(document.querySelector('.coach-contrast-feedback'))");
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate('window.scrollTo(0,0)');await shot('listening-coach-mobile');
assert.equal(await evaluate('document.documentElement.scrollWidth>document.documentElement.clientWidth'),false,'No horizontal overflow at 390px');
// Seed yesterday's memory to verify a delayed blind review without waiting a day.
await evaluate(`(()=>{const p=JSON.parse(localStorage.getItem('ouvir-ingles:v4:decoding-progress'));p.memories={};p.memories['E06']={due:Date.now()-1000,interval:1,reviews:0,lapses:0,lastStudied:Date.now()-86400000,lastScore:100};localStorage.setItem('ouvir-ingles:v4:decoding-progress',JSON.stringify(p));location.reload();})()`);
await waitFor("Boolean(document.querySelector('.decoding-coach'))");await click('Revisão surpresa · 1');
await waitFor("Boolean(document.querySelector('#blind-dictation'))");
const review=data.clips.find(c=>c.id==='E06');
assert.equal(await evaluate(`document.body.innerText.includes(${JSON.stringify(review.english)})`),false);
await click('Ouvir em 1×');await waitFor("document.querySelector('.coach-blind-player small').textContent.includes('Áudio ouvido')");
await type('#blind-dictation',review.english);await click('Conferir este teste');await click('Claro em 1×');
await waitFor("Boolean(document.querySelector('.coach-complete'))");await click('Voltar à trilha');
assert.equal(await evaluate("JSON.parse(localStorage.getItem('ouvir-ingles:v4:decoding-progress')).memories.E06.delayedScore"),100);
await shot('listening-retention-mobile');
await evaluate(`(()=>{localStorage.setItem('ouvir-ingles:v4:decoding-settings',JSON.stringify({autoAdvance:true,repeats:5,gap:600,minutes:75,speaker:'Jeanna'}));location.reload();})()`);
await waitFor("Boolean(document.querySelector('.decoding-coach'))");await click('Começar próxima lição');
await waitFor("document.querySelector('.coach-session-head').textContent.includes('Onde uma palavra termina?')");
await click('Sair da sessão');
assert.equal(exceptions.length,0,exceptions.join('\n'));
assert.deepEqual(await evaluate('window.__audioFailures'),[],'Audio must work with the normal browser autoplay policy');
console.log('UI: full human-audio cycle, word selection, stop, blind transcript removal, automatic next audio, delayed retention, narrow-speaker progression, contrast and mobile layout passed.');
socket.close();
